version: '2.4'
services:
 # Nginx server configuration   
  web:
    build:
      dockerfile: ./nginx/Dockerfile
      context: "."
    image: php-nginx
    volumes:
      - ./:/app
    container_name: webserver_semesta
    networks:
      semesta_network:
        ipv4_address: 172.29.0.2
    ports:
      - "80:80"
 # Php-fpm configuration
  php:
    build:
      dockerfile: ./php/Dockerfile
      context: "."
    image: php-fpm
    env_file:
      - ./database/database.env
    container_name: php_semesta
    networks:
      semesta_network:
        ipv4_address: 172.29.0.3  
    volumes:
      - ./:/app
 # Mysql configuration
  mysql:
    build: 
      context: ./mysql
    container_name: mysql_semesta
    restart: always
    env_file:
        - ./database/database.env
    networks:
      semesta_network:
        ipv4_address: 172.29.0.4       
    ports:
        - "3306:3306"
    volumes:
        - /dbdata:/var/lib/mysql
  #PhpmyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      semesta_network:
        ipv4_address: 172.29.0.5  
    ports:
        - "8090:80"
    links: 
        - mysql:db
networks:
    semesta_network:
        ipam:
            config:
               - subnet: 172.29.0.0/28
volumes:
    dbdata: 

