version: '2.3'
services:
 # Koonfigurasi untuk NGINX   
  web:
    build: ./nginx/
    container_name: webserver_semesta
    links:
      - mysql
      - php
    volumes:
      - ./content:/var/www/html
    ports:
      - "80:80"
 # Konfigurasi untuk PHP
  php:
    image: php:8.1-fpm
    container_name: php_semesta
    volumes:
      - ./content:/var/www/html
      - ./php:/usr/local/etc/php/php.ini
 # Konfigurasi untuk MySQL
  mysql:
    image: mysql:latest
    container_name: mysql_semesta
    restart: always
    environment:
        - MYSQL_DATABASE=semesta
        - MYSQL_ROOT_PASSWORD=islam
        - MYSQL_USER=islam
        - MYSQL_PASSWORD=islam321
    ports:
        - "3306:3306"
    volumes:
        - /dbdata:/var/lib/mysql
  #Addtional phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
        - "8090:80"
    links: 
        - mysql:db
volumes:
  dbdata:
